### ISSUE TITLE
现在还是半成品呢。。

### ISSUE THREAD

**Issue by linving** [WuXiaolong/WeWin#1]
现在还是半成品呢。。

图片，笑话的数据哪里来的？

**Comment by WuXiaolong** [comment]
对，还在更新呢，没有完全做好，数据爬网站的，你看看代码就知道了‍

------------------ 原始邮件 ------------------
发件人: "linving";notifications@github.com;
发送时间: 2014年10月24日(星期五) 凌晨0:27
收件人: "WuXiaolong/WeWin"WeWin@noreply.github.com; 

主题: [WeWin] 现在还是半成品呢。。 (#1)

现在还是半成品呢。。

图片，笑话的数据哪里来的？

**Comment by sorcerdu** [comment]
sorry，不好意思，原来是watch的项目有动态会有邮件通知。

**Comment by vvooo2009** [comment]
可以转为eclipse吗？

**Comment by WuXiaolong** [comment]
Android Studio的项目是不能导入Eclipse，反之却可以，骚年，还是学学Android Studio，未来开发的Android的工具

**Comment by renhua91** [comment]
楼主：刚下了一个Android Studio，导入的时候选了Use grade wrapper 结果出现
Could not fetch model of type 'IdeaProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.2.1-all.zip'.
A problem occurred configuring project ':app'.
A problem occurred configuring project ':app'.
A problem occurred configuring project ':libraries:StaggeredGridView'.
Could not resolve all dependencies for configuration ':libraries:StaggeredGridView:_debugCompile'.
Could not find com.android.support:support-v4:21.0.2.
Searched in the following locations:
    https://jcenter.bintray.com/com/android/support/support-v4/21.0.2/support-v4-21.0.2.pom
    https://jcenter.bintray.com/com/android/support/support-v4/21.0.2/support-v4-21.0.2.jar
Required by:
    WeWin-master.libraries:StaggeredGridView:unspecified

Consult IDE log for more details (Help | Show Log)

这个瀑布流的为啥找不到呢？是我网络的问题嘛？有没有什么解决方法？

**Comment by renhua91** [comment]
另外我访问了一下https://jcenter.bintray.com，发现目录到android下面就没有support子目录了。。
